#!/usr/bin/perl -CSDAL

use warnings;
use strict;

fork and exit;
open STDIN, "/dev/null" or die $!;
open STDOUT, ">/dev/null" or die $!;
open STDERR, ">/dev/null" or die $!;

system "/usr/lib/iserv/sleep_exec_once", "10", "scmc_newconf", "iservchk", "-a", "cert", "apache", "bind";
