#!/usr/bin/perl -T -CSDAL

use warnings;
use strict;
use utf8;
use Bytes::Random::Secure;
use Cwd qw(abs_path);
use IServ::DB;
use scmcauth;
use Stsbl::IServ::IO;
use Stsbl::IServ::Log;
use Stsbl::IServ::SCMC;
use Stsbl::IServ::Security;

my $m_ip = qr/[\d.:]{1,64}/;

my $fn_master_passwd = "/etc/stsbl/scmcmasterpasswd";

my $login_pwd = $ENV{PASSWORD} // $ENV{SESSPW};
my ($login_ip) = ($ENV{IP} // "") =~ /^($m_ip)$/;
my ($login_ip_fwd) = ($ENV{IPFWD} // "") =~ /^($m_ip)$/;
my $scmc_sessionpw = $ENV{SCMC_SESSIONPW};
my ($arg) = ($ENV{ARG} // "") =~ /^(.*)$/;
my ($old_masterpw) = ($ENV{SCMC_OLDMASTERPW} // "") =~ /^(.*)$/;
my ($new_masterpw) = ($ENV{SCMC_NEWMASTERPW} // "") =~ /^(.*)$/;
my $sudo_uid = $ENV{SUDO_UID};

undef %ENV;
$ENV{PATH} = "/usr/sbin:/usr/bin:/sbin:/bin";
$ENV{SUDO_UID} = $sudo_uid;

if (@ARGV < 2)
{
  print STDERR "Usage: scmcadm COMMAND ARGS\n\n";
  print STDERR "Command getdata: LOGIN SERVERID [YEARS]\n";
  print STDERR "Command putdata: LOGIN SERVERID ZIPFILE [YEARS]\n";
  print STDERR "Command storekey: LOGIN SERVERID KEYFILE\n";
  print STDERR "Command deletekey: LOGIN SERVERID\n";
  print STDERR "Command masterpasswdempty: LOGIN\n";
  print STDERR "Command setuserpasswd: LOGIN DESTACT\n";
  print STDERR "Command deleteuserpasswd: LOGIN DESTCACT\n";
  print STDERR "Command setmasterpasswd: LOGIN\n\n";
  print STDERR "Environment: ARG, PASSWORD, IP, IPWD, SCMC_SESSIONPW, SCMC_OLDMASTERPW, SCMC_NEWMASTERPW\n";
  print STDERR "Return of getdata: Folder path of created zip file on STDOUT.\n";
  exit 1;
}

my $cmd = shift @ARGV;
my $login_act = shift @ARGV;

my $has_years = 0;
$has_years = 1 if ($cmd eq "getdata" and @ARGV >= 4 - 2) or ($cmd eq "putdata" and @ARGV >= 5 - 2);

set_ips $login_ip, $login_ip_fwd;
set_credentials $login_act, $login_pwd;
sessauth_auth "scmcadm";

sub check_server_id($)
{
  my $server_id = shift;
  $server_id =~ /^\d+$/i or error "Invalid Server ID!";
  error "Invalid Server ID!" if not IServ::DB::Do "SELECT 1 FROM scmc_servers WHERE ID = ?", $server_id;
}

sub get_server_data($)
{
  return IServ::DB::SelectRow "SELECT s.SSHAct, s.TomcatType, s.Host, h.IP FROM scmc_servers s ".
    "JOIN hosts h ON (s.Host = h.Name) WHERE s.ID = ?", shift;
}
sub ssh($$$$)
{
  my ($server_key, $server_user, $server_ip, $cmd) = @_;
  system("ssh", "-i", $server_key, 
    "-o", "StrictHostKeyChecking=no", 
    "-o", "UserKnownHostsFile=/dev/null",
    "-o", "ConnectTimeout=30",
    "-o", "LogLevel=ERROR",
    "-o", "PreferredAuthentications=publickey",
    "$server_user\@$server_ip",
    $cmd) == 0
      or die "ssh failed: $!";
}

sub scp($$$)
{
  my ($server_key, $src, $dest) = @_;
  system("scp", "-i", $server_key, "-o",
    "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null",
    "-o", "ConnectTimeout=30",
    "-o", "LogLevel=ERROR",
    "-o", "PreferredAuthentications=publickey",
    "-r",
    $src,
    $dest) == 0
      or die "scp failed: $!";
}

sub check_path($) 
{
  my $realpath = abs_path shift;
  $realpath =~ /\/tmp\/stsbl-iserv-scmc-(.*)/ or Stsbl::IServ::IO::error "Invalid file path!";
}

sub validate_years(@)
{
  foreach my $year (@_)
  {
    Stsbl::IServ::IO::error "Year $year invalid!" if not $year =~ /([0-9]|[1][0-3])/;
  }
}

sub req_scmc_auth
{
  scmcauth::simple_login $login_act, $login_pwd, "scmcadm", $scmc_sessionpw or Stsbl::IServ::IO::error "scmc auth login failed!";
}

my $random = new Bytes::Random::Secure();

if ($cmd eq "getdata")
{
  req_auth;
  req_priv "scmc_access_frontend";
  req_scmc_auth; 

  my $server_id = shift @ARGV;
  if ($server_id =~ /^(.*)$/)
  {
    $server_id = $1;
  }
  check_server_id $server_id;

  my @years;
  if ($has_years)
  {
    @years = split /,/, shift(@ARGV);
    validate_years @years;
  }

  my ($server_user, $server_type, $server_name, $server_ip) = get_server_data $server_id;
  my $server_key = "/var/lib/stsbl/scmc/keys/$server_id";
  Stsbl::IServ::IO::error "SSH-Schlüssel fehlt für Server $server_name." if not -f $server_key;

  my $dest_dir = "/tmp/stsbl-iserv-scmc-".$random->string_from('0123456789', 10)."/";
  my $dest_zip = "/tmp/stsbl-iserv-scmc-".$random->string_from('0123456789', 10).".zip";

  # untaint variables (TODO why is this neccessary?!)
  if ($dest_dir =~ /^(.*)$/) {
    $dest_dir = $1;
  } else {
    die "Failed to untaint data!";
  }
  if ($dest_zip =~ /^(.*)$/) {
    $dest_zip = $1;
  } else {
    die "Failed to untaint data!";
  }

  # Should never happen
  die "Insecure destination!" if -d $dest_dir;
  die "Insecure zip path!" if -f $dest_zip;

  mkdir $dest_dir, 00700 or die "Failed to create directory $dest_dir: $!";

  if ($has_years)
  {
    foreach my $year (@years)
    {
      $year =~ /^(.*)$/;
      scp $server_key, "$server_user\@$server_ip:/Zeugnisse/Jahrgang$1/", $dest_dir;
    }
  } else 
  {
    scp $server_key, "$server_user\@$server_ip:/Zeugnisse/Jahrgang*/", $dest_dir;
  }

  chdir $dest_dir or die "Failed to chdir to $dest_dir: $!";
  system("zip", "-q", "-r", $dest_zip, "./") == 0 or
    die "Creating of archive failed: $!";
  my (undef, undef, $www_data_uid) = getpwnam "www-data";
  chown $www_data_uid, 0, $dest_zip;
  chmod 00600, $dest_zip;

  system("rm", "-rf",  $dest_dir) == 0 or warn "Failed to remove destination directory: $!"; 
  print "path=$dest_zip\n";
} elsif ($cmd eq "putdata") 
{
  req_auth;
  req_priv "scmc_access_frontend";
  req_scmc_auth;

  my $server_id = shift @ARGV;
  if ($server_id =~ /^(.*)$/)
  { 
    $server_id = $1;
  }
  check_server_id $server_id;

  my $src_zip = shift @ARGV;

  my @years;
  if ($has_years)
  {
    @years = split /,/, shift(@ARGV);
    validate_years @years;
  }

  my ($server_user, $server_type, $server_name, $server_ip) = get_server_data $server_id;
  my $server_key = "/var/lib/stsbl/scmc/keys/$server_id";
  Stsbl::IServ::IO::error "SSH-Schlüssel fehlt für Server $server_name." if not -f $server_key;

  my $dest_dir = "/tmp/stsbl-iserv-scmc-".$random->string_from('0123456789', 10)."/";

  # untaint variables (TODO why is this neccessary?!)
  if ($dest_dir =~ /^(.*)$/) {
    $dest_dir = $1;
  } else {
    die "Failed to untaint data!";
  }
  if ($src_zip =~ /^(.*)$/) {
    $src_zip = $1;
  } else {
    die "Failed to untaint data!";
  }
  
  # check path to prevent illegal files
  check_path $src_zip;

  # Should never happen
  die "Insecure destination!" if -d $dest_dir;
  die "Invalid zip file!" if not -f $src_zip;

  if ($has_years)
  {
    foreach my $year (@years)
    {
      $year =~ /^(.*)$/;
      ssh $server_key, $server_user, $server_ip, "sh -c \"rm -rfv /Zeugnisse/Jahrgang$1/ > /Zeugnisse/delete.log\"";
    }
  } else
  {
    ssh $server_key, $server_user, $server_ip, "sh -c \"rm -rfv /Zeugnisse/Jahrgang*/ > /Zeugnisse/delete.log\"";
  }

  mkdir $dest_dir, 00700 or die "Failed to create directory $dest_dir: $!";
  chdir $dest_dir or die "Failed to chdir to $dest_dir: $!";
  system("unzip", "-q", $src_zip) == 0 or die "Failed to unzip archive $src_zip: $!"; 
  
  if ($has_years)
  {
    foreach my $year (@years)
    {
      $year =~ /^(.*)$/;
      scp $server_key, "./Jahrgang$1", "$server_user\@$server_ip:/Zeugnisse/";
    }
  } else
  {
    scp $server_key, "./", "$server_user\@$server_ip:/Zeugnisse/";
  }

  chdir "/"; 
  system("rm", "-rf", $dest_dir)  == 0 or warn "Failed to remove destination directory: $!";;

  ssh $server_key, $server_user, $server_ip, "sh -c \"find /Zeugnisse/ -type f -exec chmod -v 664 {} \\; > /Zeugnisse/chmod-files.log\"";
  ssh $server_key, $server_user, $server_ip, "sh -c \"find /Zeugnisse/ -type d -exec chmod -v 2775 {} \\; > /Zeugnisse/chmod-dirs.log\"";
  ssh $server_key, $server_user, $server_ip, "sh -c \"chgrp -Rv $server_type /Zeugnisse/ > /Zeugnisse/chgrp.log\"";

  Stsbl::IServ::Log::write_for_module "Zeugnisdaten auf den Server \"$server_name\" hochgeladen", "School Certificate Manager Connector";
} elsif ($cmd eq "storekey")
{
  req_admin;
  req_priv "scmc_admin";

  my $server_id = shift @ARGV;
  if ($server_id =~ /^(.*)$/)
  { 
    $server_id = $1;
  }
  my $key_file = shift @ARGV;
  if ($key_file =~ /^(.*)$/)
  { 
    $key_file = $1;
  }
  check_server_id $server_id;
  check_path $key_file;
  my $dest = "/var/lib/stsbl/scmc/keys/$server_id";
  open FH, ">", $dest or die "Failed to open file $dest: $!";
  print FH "";
  close FH;

  chown 0, 0, $dest;
  chmod 00600, $dest;
  system("cp", "-f", $key_file, $dest) == 0 or warn "Failed to copy key: $!";
  unlink $key_file;

} elsif ($cmd eq "deletekey") {
  req_admin;
  req_priv "scmc_admin";

  my $server_id = shift @ARGV;
  if ($server_id =~ /^(.*)$/)
  {
    $server_id = $1;
  }

  # no check_server_id checking here, as the host could already deleted from the database
  Stsbl::IServ::IO::error "Invalid Server ID!" if not $server_id =~ /^\d+$/i;

  my $key = "/var/lib/stsbl/scmc/keys/$server_id";
  unlink $key if -f $key;
} elsif ($cmd eq "masterpasswdempty")
{
  req_auth;
  req_one_priv ("scmc_access_frontend", "scmc_admin");
  
  if (-s $fn_master_passwd == 0)
  {
    print "res=true\n";
  } else
  {
    print "res=false\n";
  }
} elsif ($cmd eq "setuserpasswd")
{
  req_admin;
  req_priv "scmc_admin";

  my $user = shift @ARGV;
  Stsbl::IServ::SCMC::SetUserPasswd $user, $arg;
} elsif ($cmd eq "deleteuserpasswd")
{
  req_admin;
  req_priv "scmc_admin";

  my $user = shift @ARGV;
  Stsbl::IServ::SCMC::DeleteUserPasswd $user;
} elsif ($cmd eq "setmasterpasswd")
{
  req_admin;
  req_priv "scmc_admin";
 
  my $old;
  $old = $old_masterpw if defined $old_masterpw and not $old_masterpw eq "";
  Stsbl::IServ::SCMC::SetMasterPasswd $new_masterpw, $old;
} else 
{
  error "Unknown command $cmd!";
}
