#!/bin/bash -e

echo -en "$(tput setaf 1)Are you sure that you want to reset the master password? (y/N) $(tput op)"
read answer

if [ "$answer" = "y" ] || [ "$anwser" = "Y" ]
then
  echo "Deleting master password ..."
  rm -f /var/lib/stsbl/scmc/auth/masterpassword.{pwd,salt}
  echo "Running iservchk scmc ..."
  iservchk scmc
  echo
  echo -e "$(tput setaf 2)Success, you may now set the master password in the IDesk under $(tput sgr 0 1)$(tput setaf 2)Administration > Modules > Certifcate Management$(tput sgr 0 0) $(tput setaf 2)again."
  echo -en "Press enter to continue ...$(tput op)"
  read
fi
