#!/bin/bash -e

export BASHGT_DOMAIN=iserv

. /usr/lib/bash-gettext/functions.sh

echo -en "$(tput setaf 1)$(_ "Are you sure that you want to reset the master password? (y/N)") $(tput op)"
read answer

if [ "$answer" = "y" ] || [ "$anwser" = "Y" ]
then
  echo $(_ "Deleting master password ...")
  rm -f /var/lib/stsbl/scmc/auth/masterpassword.{pwd,salt}
  echo $(_ "Running iservchk scmc ...")
  iservchk scmc
  echo
  echo -e "$(tput setaf 2)$(_ "Success, you may now set the master password in the IDesk under ")$(tput sgr 0 1)$(tput setaf 2)$(_ "Administration > Modules > Certifcate Management")$(tput sgr 0 0) $(tput setaf 2)$(_ "again.")"
  echo -en $(_ "Press enter to continue ...")$(tput op)
  read
fi
