services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Stsbl\ScmcBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Resources,Tests}'

    Stsbl\ScmcBundle\Controller\:
        public: true
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']

    Stsbl\ScmcBundle\EventListener\KernelControllerSubscriber:
        bind:
            $resolver: '@controller_resolver'
